#!/usr/bin/env python3
"""Export project study notes to the existing VitePress blog (stdlib only)."""
import argparse
import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = Path('docs/projects/java/course-system-notes')
MARKER = '<!-- Generated by Intelligent-course-system/scripts/sync-study-notes.py -->'


def digest(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def run():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--blog-dir', required=True, type=Path)
    parser.add_argument('--dry-run', action='store_true', help='Report changes without writing')
    args = parser.parse_args()
    blog = args.blog_dir.expanduser().resolve()
    if not (blog / 'docs/.vitepress/config.mts').is_file():
        raise ValueError('目标不是当前支持的 VitePress 博客：缺少 docs/.vitepress/config.mts')
    source = ROOT / 'docs/study-notes'
    target = blog / DESTINATION
    if target.resolve() != target:
        raise ValueError('同步目录不能经过符号链接')
    manifest = target / '.sync-manifest.json'
    previous = json.loads(manifest.read_text()) if manifest.exists() else {}
    notes = sorted(p for p in source.glob('*.md') if p.name != 'README.md')
    if not notes:
        raise ValueError('没有找到学习笔记')
    names = {p.name for p in notes}
    outputs, state, rows = {}, {}, []
    today = date.today().isoformat()
    for path in notes:
        raw = path.read_text(encoding='utf-8')
        title = re.search(r'^# (.+)$', raw, re.M)
        if not title or raw.startswith('---'):
            raise ValueError(f'{path.name}: 原稿需使用一级标题，不支持已有 frontmatter')
        dates = re.findall(r'^### (\d{4}-\d{2}-\d{2})', raw, re.M)
        for value in dates:
            date.fromisoformat(value)
        old = previous.get(path.name, {})
        created = old.get('created', min(dates) if dates else today)
        updated = old.get('updated', max(dates) if dates else today)
        if old and old.get('source_hash') != digest(raw):
            updated = max(today, updated, max(dates) if dates else today)
        # Only rewrite links outside fenced code. Refuse unsupported local links
        # rather than silently publishing a broken asset/source link.
        body, fence = [], None
        for line in raw.splitlines(keepends=True):
            match = re.match(r'^\s*(`{3,}|~{3,})', line)
            if match:
                token = match[1]
                if fence is None:
                    fence = token
                elif token[0] == fence[0] and len(token) >= len(fence):
                    fence = None
                body.append(line)
                continue
            if fence is None:
                def rewrite(match):
                    link = match[1]
                    if re.match(r'^[a-zA-Z][\w+.-]*:', link) or link.startswith('#'):
                        return match[0]
                    filename, sep, anchor = link.partition('#')
                    filename = filename.removeprefix('./')
                    if filename == 'README.md':
                        filename = 'overview.md'
                    elif filename not in names:
                        raise ValueError(f'{path.name}: 暂不支持的本地链接 {link}；请先适配资源同步')
                    return '](' + filename + (sep + anchor if sep else '') + ')'
                line = re.sub(r'\]\(([^)]+)\)', rewrite, line)
                if re.match(r'^\s*\[[^\]]+\]:', line):
                    raise ValueError(f'{path.name}: 暂不支持引用式链接，请使用行内链接')
            body.append(line)
        heading = title[0]
        content = ''.join(body).replace(heading, heading + '\n\n'
            f'首次收录：{created} · 最近更新：{updated}\n\n'
            '[返回学习笔记目录](overview.md)', 1)
        content = (f'---\ntitle: {json.dumps(title[1], ensure_ascii=False)}\n'
                   f'date: {updated}\ncreated: {created}\n'
                   'category: 项目学习笔记\ntags: [智能课程系统, 学习笔记]\n---\n\n'
                   + MARKER + '\n\n' + content)
        outputs[path.name] = content
        state[path.name] = dict(created=created, updated=updated,
                                source_hash=digest(raw), output_hash=digest(content))
        rows.append((updated, title[1], path.name))
    rows.sort(key=lambda row: (row[0], row[2]), reverse=True)
    overview = ('---\ndate: ' + rows[0][0] + '\n---\n\n' + MARKER
                + '\n\n# 智能课程系统学习笔记\n\n'
                '按主题回顾项目中的原理、实现与易错点。建议先读核心结论，再尝试文末的复习自测，最后核对答案。\n\n'
                '[查看项目复盘](../course-system.md)\n\n'
                '| 主题 | 最近更新 |\n| --- | --- |\n')
    overview += ''.join(f'| [{title}]({name}) | {updated} |\n' for updated, title, name in rows)
    outputs['overview.md'] = overview
    state['overview.md'] = {'output_hash': digest(overview)}
    changes = []
    # Validate every destination before writing anything.
    for name, content in outputs.items():
        destination = target / name
        if destination.is_symlink():
            raise ValueError(f'拒绝写入符号链接：{destination}')
        existing = destination.read_text(encoding='utf-8') if destination.exists() else None
        if existing is not None and existing != content:
            if digest(existing) != previous.get(name, {}).get('output_hash'):
                raise ValueError(f'博客文章存在未同步的手工改动或同名文件：{destination}；请先将内容合并回原稿')
        if existing != content:
            changes.append(name)
            print(('新增 ' if existing is None else '更新 ') + str(destination))
    stale = set(previous) - set(state)
    for name in sorted(stale):
        print(f'保留原稿已移除的文章（请手动处理）：{name}')
        state[name] = previous[name]
    manifest_text = json.dumps(state, ensure_ascii=False, indent=2, sort_keys=True) + '\n'
    if manifest.is_symlink():
        raise ValueError('同步清单不能是符号链接')
    if not args.dry_run:
        target.mkdir(parents=True, exist_ok=True)
        for name in changes:
            (target / name).write_text(outputs[name], encoding='utf-8')
        if not manifest.exists() or manifest.read_text() != manifest_text:
            manifest.write_text(manifest_text, encoding='utf-8')
    print(f'{"预览" if args.dry_run else "同步"}完成：{len(notes)} 篇笔记，{len(changes)} 个页面变化。')


if __name__ == '__main__':
    try:
        run()
    except (ValueError, OSError) as error:
        print(f'同步失败：{error}', file=sys.stderr)
        sys.exit(1)
